apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kubernetes
  - ../../samples
images:
  - name: docker.io/dynatrace/dynatrace-operator:snapshot
    newName: docker.io/dynatrace/dynatrace-operator
    newTag: v0.2.1
  - name: quay.io/dynatrace/dynatrace-operator:snapshot
    newName: docker.io/dynatrace/dynatrace-operator
    newTag: v0.2.1
