# Copyright 2020 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v2
name: dynatrace-operator
description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
icon: https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png
home: https://www.dynatrace.com/
type: application
version: 0.0.0-snapshot
appVersion: 0.0.0-snapshot
kubeVersion: '>=1.21-0'
maintainers:
- name: 0sewa0
  email: marcell.sevcsik@dynatrace.com
- name: chrismuellner
  email: christoph.muellner@dynatrace.com
- name: luhi-DT
  email: lukas.hinterreiter@dynatrace.com
sources:
- https://github.com/Dynatrace/dynatrace-operator
