apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../common/activegate
  - ../common/kubernetes-monitoring
  - ../common/oneagent
  - ../common/operator
  - ../common/routing
  - ../common/webhook
  - ../crd
