apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../common/data-ingest
  - ../common/activegate
  - ../common/kubernetes-monitoring
  - ../common/oneagent
  - ../common/operator
  - ../common/routing
  - ../common/webhook
  - ../crd/default
images:
  - name: quay.io/dynatrace/dynatrace-operator:snapshot
    newName: quay.io/dynatrace/dynatrace-operator
    newTag: snapshot-release-0-3
    