apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- oneagent/securitycontextconstraints.yaml
- oneagent/securitycontextconstraints-unprivileged.yaml
bases:
  - ../common
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: dynatrace-operator
      namespace: dynatrace
    path: operator/deployment-operator-patch.yaml
  - target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: dynatrace-dynakube-oneagent
      namespace: dynatrace
    path: operator/serviceaccount-patch.yaml
  - target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: dynatrace-operator
      namespace: dynatrace
    path: operator/serviceaccount-patch.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: dynakubes.dynatrace.com
    path: patchesocp3.11/crd-patch.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: dynatrace-operator
    path: operator/clusterrole-patch.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: dynatrace-operator
    path: operator/clusterrole-patch.yaml