apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- oneagent/securitycontextconstraints.yaml
- oneagent/securitycontextconstraints-unprivileged.yaml
bases:
  - ../common/activegates
  - ../common/data-ingest
  - ../common/kubernetes-monitoring
  - ../common/oneagent
  - ../common/operator
  - ../common/routing
  - ../crd/ocp311
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: dynatrace-operator
      namespace: dynatrace
    path: operator/deployment-operator-patch.yaml
  - target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: dynatrace-dynakube-oneagent
      namespace: dynatrace
    path: operator/serviceaccount-patch.yaml
  - target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: dynatrace-operator
      namespace: dynatrace
    path: operator/serviceaccount-patch.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: dynatrace-operator
    path: operator/clusterrole-patch.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: dynatrace-operator
    path: operator/clusterrole-patch.yaml