apiVersion: v1
automountServiceAccountToken: false
imagePullSecrets:
- name: redhat-connect
- name: redhat-connect-sso
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: oneagent
    app.kubernetes.io/name: dynatrace-operator
    app.kubernetes.io/version: 0.10.1
  name: dynatrace-dynakube-oneagent-privileged
