{{- if (.Values.webhook).highAvailability }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dynatrace-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.webhookLabels" . | nindent 4 }}
spec:
  {{- toYaml .Values.webhook.podDisruptionBudget | nindent 2 }}
{{- end }}
