{{- if not (empty (include "dynatrace-operator.webhook.podDisruptionBudget" .))}}
# v1 version supported since k8s 1.21
apiVersion: {{ .Capabilities.APIVersions.Has "policy/v1" | ternary "policy/v1" "policy/v1beta1" }}
kind: PodDisruptionBudget
metadata:
  name: dynatrace-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.webhookLabels" . | nindent 4 }}
spec:
  {{- include "dynatrace-operator.webhook.podDisruptionBudget" . | nindent 2 }}
  selector:
    matchLabels:
      {{- include "dynatrace-operator.webhookSelectorLabels" . | nindent 6 }}
{{- end }}
