{{- $platformIsSet := printf "%s" (required "Platform needs to be set to kubernetes, openshift " (include "dynatrace-operator.platformSet" .))}}
{{ if (.Values.webhook).enableHighAvailability }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dynatrace-webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook
{{ end }}
