apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: dynatrace-webhook
  labels:
    dynatrace.com/operator: dynakube
    internal.dynatrace.com/component: webhook
webhooks:
  - name: webhook.dynatrace.com
    reinvocationPolicy: IfNeeded
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "pods" ]
        scope: Namespaced
    namespaceSelector:
      matchExpressions:
        - key: oneagent.dynatrace.com/instance
          operator: Exists
    clientConfig:
      service:
        name: dynatrace-webhook
        namespace: dynatrace
        path: /inject
    admissionReviewVersions: [ "v1beta1" ]
