apiVersion: v1
entries:
  dynatrace-operator:
  - apiVersion: v2
    appVersion: 0.4.1
    created: '2022-02-01T13:14:01.982041685Z'
    description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
    digest: 2918b3a2ad3ecfea04902d4161499935f3f7e83b0a8889d34c22fc00ecbcb35a
    home: https://www.dynatrace.com/
    icon: https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png
    maintainers:
    - email: marcell.sevcsik@dynatrace.com
      name: 0sewa0
    - email: christoph.muellner@dynatrace.com
      name: chrismuellner
    - email: lukas.hinterreiter@dynatrace.com
      name: luhi-DT
    name: dynatrace-operator
    sources:
    - https://github.com/Dynatrace/dynatrace-operator
    type: application
    urls:
    - https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/master/config/helm/repos/stable/dynatrace-operator-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 0.4.0
    created: '2022-01-25T12:25:43.110745598Z'
    description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
    digest: 2e7bbc3b1424db289776d6b5fd839c1bd924ea20d9629e5cfdf4f8b1b2c12dec
    home: https://www.dynatrace.com/
    icon: https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png
    maintainers:
    - email: marcell.sevcsik@dynatrace.com
      name: 0sewa0
    - email: christoph.muellner@dynatrace.com
      name: chrismuellner
    - email: lukas.hinterreiter@dynatrace.com
      name: luhi-DT
    name: dynatrace-operator
    sources:
    - https://github.com/Dynatrace/dynatrace-operator
    type: application
    urls:
    - https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/master/config/helm/repos/stable/dynatrace-operator-0.4.0.tgz
    version: 0.4.0
generated: '2022-02-01T14:55:21.503397908Z'
