apiVersion: v1
entries:
  dynatrace-operator:
  - apiVersion: v2
    appVersion: 0.6.0
    created: '2022-05-06T09:54:25.498445534Z'
    description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
    digest: 5740d1d7d1e895d969717a8160d02493224086366282628c0c2e148ca8f80006
    home: https://www.dynatrace.com/
    icon: https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png
    maintainers:
    - email: marcell.sevcsik@dynatrace.com
      name: 0sewa0
    - email: christoph.muellner@dynatrace.com
      name: chrismuellner
    - email: lukas.hinterreiter@dynatrace.com
      name: luhi-DT
    name: dynatrace-operator
    sources:
    - https://github.com/Dynatrace/dynatrace-operator
    type: application
    urls:
    - https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.6.0/dynatrace-operator-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 0.5.0
    created: '2022-03-16T09:20:52.737361919Z'
    description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
    digest: f1059a1e1b08e84537a5210bd6dce072953a197629fe5d21e85a7ceb2235f88c
    home: https://www.dynatrace.com/
    icon: https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png
    maintainers:
    - email: marcell.sevcsik@dynatrace.com
      name: 0sewa0
    - email: christoph.muellner@dynatrace.com
      name: chrismuellner
    - email: lukas.hinterreiter@dynatrace.com
      name: luhi-DT
    name: dynatrace-operator
    sources:
    - https://github.com/Dynatrace/dynatrace-operator
    type: application
    urls:
    - https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/master/config/helm/repos/stable/dynatrace-operator-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 0.4.2
    created: '2022-02-15T16:50:00.153390163Z'
    description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
    digest: bd5ec00b917d84157bbc0a2676581979dc7c7f56728703436731a3cf94be7165
    home: https://www.dynatrace.com/
    icon: https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png
    maintainers:
    - email: marcell.sevcsik@dynatrace.com
      name: 0sewa0
    - email: christoph.muellner@dynatrace.com
      name: chrismuellner
    - email: lukas.hinterreiter@dynatrace.com
      name: luhi-DT
    name: dynatrace-operator
    sources:
    - https://github.com/Dynatrace/dynatrace-operator
    type: application
    urls:
    - https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/master/config/helm/repos/stable/dynatrace-operator-0.4.2.tgz
    version: 0.4.2
  - apiVersion: v2
    appVersion: 0.4.1
    created: '2022-02-01T13:14:01.982041685Z'
    description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
    digest: c343ea54012d0a1c6680e69320ebc6335beb05b1c8c3d91e7eba081579bf8728
    home: https://www.dynatrace.com/
    icon: https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png
    maintainers:
    - email: marcell.sevcsik@dynatrace.com
      name: 0sewa0
    - email: christoph.muellner@dynatrace.com
      name: chrismuellner
    - email: lukas.hinterreiter@dynatrace.com
      name: luhi-DT
    name: dynatrace-operator
    sources:
    - https://github.com/Dynatrace/dynatrace-operator
    type: application
    urls:
    - https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/master/config/helm/repos/stable/dynatrace-operator-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 0.4.0
    created: '2022-01-25T12:25:43.110745598Z'
    description: The Dynatrace Operator Helm chart for Kubernetes and OpenShift
    digest: 2e7bbc3b1424db289776d6b5fd839c1bd924ea20d9629e5cfdf4f8b1b2c12dec
    home: https://www.dynatrace.com/
    icon: https://assets.dynatrace.com/global/resources/Signet_Logo_RGB_CP_512x512px.png
    maintainers:
    - email: marcell.sevcsik@dynatrace.com
      name: 0sewa0
    - email: christoph.muellner@dynatrace.com
      name: chrismuellner
    - email: lukas.hinterreiter@dynatrace.com
      name: luhi-DT
    name: dynatrace-operator
    sources:
    - https://github.com/Dynatrace/dynatrace-operator
    type: application
    urls:
    - https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/master/config/helm/repos/stable/dynatrace-operator-0.4.0.tgz
    version: 0.4.0
generated: '2022-05-06T09:54:25.487121387Z'
