apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - csi/securitycontextconstraints-csidriver.yaml
  - oneagent/securitycontextconstraints.yaml
  - oneagent/securitycontextconstraints-unprivileged.yaml
bases:
  - ../common
  - ../common/csi
  - ../common/webhook
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: dynatrace-operator
      namespace: dynatrace
    path: operator/deployment-operator-patch.yaml
  - target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: dynatrace-dynakube-oneagent
      namespace: dynatrace
    path: operator/serviceaccount-patch.yaml
  - target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: dynatrace-operator
      namespace: dynatrace
    path: operator/serviceaccount-patch.yaml
  - target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: dynatrace-webhook
      namespace: dynatrace
    path: operator/serviceaccount-patch.yaml
