kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dynatrace-metrics
  namespace: dynatrace
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - dynatrace-metrics
    verbs:
      - use
