{{- if (and .Values.rbac.extensions.database.create .Values.rbac.extensions.create)}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynatrace-sql-extension-executor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-operator.databaseDatasourceLabels" . | nindent 4 }}
{{- end }}
