apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubernetes-all.yaml
images:
- name: quay.io/dynatrace/dynatrace-operator:snapshot
  newName: quay.io/dynatrace/dynatrace-operator
  newTag: snapshot-feature-split-csdriver
