name: E2E cleanup Kubernetes settings

on:
  schedule:
    # every Sunday at 00:00 UTC
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  cleanup-kubernetes-settings:
    name: Cleanup Kubernetes settings
    environment: E2E
    runs-on:
      - self-hosted
      - operator-e2e
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          sparse-checkout: ./hack/tenant/cleanup-kubernetes-settings.sh
      - name: Run cleanup script
        shell: bash
        env:
          TENANT_NAME: ${{ secrets.TENANT1_NAME }}
          TENANT_APITOKEN: ${{ secrets.TENANT1_APITOKEN }}
        run: |
          ./hack/tenant/cleanup-kubernetes-settings.sh
