name: GCR Deployer image
on:
  pull_request:
    branches:
      - csv-*
    paths:
      - config/helm/schema.yaml
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to checkout
        required: true
        type: string

env:
  GOOGLE_MARKETPLACE_ANNOTATION: com.googleapis.cloudmarketplace.product.service.name=services/dynatrace-operator-dynatrace-marketplace-prod.cloudpartnerservices.goog
  DEPLOYER_PLATFORMS: linux/amd64

jobs:
  build-gcr-deployer:
    name: Build GCR deployer image
    environment: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || inputs.ref }}
      - name: Prepare build parameters
        run: |
          image_tag=$(yq -e '.x-google-marketplace.publishedVersion' config/helm/schema.yaml)
          echo IMAGE=gcr.io/${{ secrets.GCR_REPOSITORY_DEPLOYER }}:$image_tag >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: gcr.io
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          platforms: ${{ env.DEPLOYER_PLATFORMS }}
          provenance: false
          context: ./config/helm
          file: ./config/helm/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
          annotations: |
            ${{ env.GOOGLE_MARKETPLACE_ANNOTATION }}
